---
title: "Supporto"
---

Il docente è a disposizione per aiutare ogni singolo studente ad avere successo nel corso. Vi incoraggio a venire a ricevimento, sia per ricevere chiarimenti individuali, sia per segnalare argomenti che vorreste vedere ripresi o approfonditi in classe.

Il ricevimento è possibile nei giorni di lezione, subito dopo la lezione, oppure su appuntamento previo accordo via e-mail.

Per le comunicazioni via e-mail, utilizzate [janek.guerrini@unipd.it](mailto:janek.guerrini@unipd.it) e inserite `[Semiotica 2026]` nell’oggetto del messaggio.

## Inclusione

L’Università di Padova offre supporti per la frequenza delle lezioni, lo studio e gli esami alle studentesse e agli studenti con disabilità, disturbi specifici dell’apprendimento (DSA) e altre condizioni di vulnerabilità.

Per informazioni sui servizi e sulle modalità di accesso, potete rivolgervi all’Ufficio Servizi agli studenti – Settore Inclusione, scrivendo a [inclusione.studenti@unipd.it](mailto:inclusione.studenti@unipd.it), e consultare la [pagina dedicata ai supporti](https://www.unipd.it/node/76518).

Vi incoraggio anche a contattare il docente per discutere le vostre esigenze e individuare, insieme al Settore Inclusione, le modalità più adatte a partecipare alle attività del corso.
